return function()
  return {
    {
      word = ":art:",
      label = "🎨 :art:",
      insertText = "🎨",
      filterText = ":art:",
    },
    {
      word = ":zap:",
      label = "⚡ :zap:",
      insertText = "⚡",
      filterText = ":zap:",
    },
    {
      word = ":fire:",
      label = "🔥 :fire:",
      insertText = "🔥",
      filterText = ":fire:",
    },
    {
      word = ":bug:",
      label = "🐛 :bug:",
      insertText = "🐛",
      filterText = ":bug:",
    },
    {
      word = ":ambulance:",
      label = "🚑 :ambulance:",
      insertText = "🚑",
      filterText = ":ambulance:",
    },
    {
      word = ":sparkles:",
      label = "✨ :sparkles:",
      insertText = "✨",
      filterText = ":sparkles:",
    },
    {
      word = ":memo:",
      label = "📝 :memo:",
      insertText = "📝",
      filterText = ":memo:",
    },
    {
      word = ":rocket:",
      label = "🚀 :rocket:",
      insertText = "🚀",
      filterText = ":rocket:",
    },
    {
      word = ":lipstick:",
      label = "💄 :lipstick:",
      insertText = "💄",
      filterText = ":lipstick:",
    },
    {
      word = ":tada:",
      label = "🎉 :tada:",
      insertText = "🎉",
      filterText = ":tada:",
    },
    {
      word = ":white_check_mark:",
      label = "✅ :white_check_mark:",
      insertText = "✅",
      filterText = ":white_check_mark:",
    },
    {
      word = ":lock:",
      label = "🔒 :lock:",
      insertText = "🔒",
      filterText = ":lock:",
    },
    {
      word = ":closed_lock_with_key:",
      label = "🔐 :closed_lock_with_key:",
      insertText = "🔐",
      filterText = ":closed_lock_with_key:",
    },
    {
      word = ":bookmark:",
      label = "🔖 :bookmark:",
      insertText = "🔖",
      filterText = ":bookmark:",
    },
    {
      word = ":rotating_light:",
      label = "🚨 :rotating_light:",
      insertText = "🚨",
      filterText = ":rotating_light:",
    },
    {
      word = ":construction:",
      label = "🚧 :construction:",
      insertText = "🚧",
      filterText = ":construction:",
    },
    {
      word = ":green_heart:",
      label = "💚 :green_heart:",
      insertText = "💚",
      filterText = ":green_heart:",
    },
    {
      word = ":arrow_down:",
      label = "⬇️ :arrow_down:",
      insertText = "⬇️",
      filterText = ":arrow_down:",
    },
    {
      word = ":arrow_up:",
      label = "⬆️ :arrow_up:",
      insertText = "⬆️",
      filterText = ":arrow_up:",
    },
    {
      word = ":pushpin:",
      label = "📌 :pushpin:",
      insertText = "📌",
      filterText = ":pushpin:",
    },
    {
      word = ":construction_worker:",
      label = "👷 :construction_worker:",
      insertText = "👷",
      filterText = ":construction_worker:",
    },
    {
      word = ":chart_with_upwards_trend:",
      label = "📈 :chart_with_upwards_trend:",
      insertText = "📈",
      filterText = ":chart_with_upwards_trend:",
    },
    {
      word = ":recycle:",
      label = "♻️ :recycle:",
      insertText = "♻️",
      filterText = ":recycle:",
    },
    {
      word = ":heavy_plus_sign:",
      label = "➕ :heavy_plus_sign:",
      insertText = "➕",
      filterText = ":heavy_plus_sign:",
    },
    {
      word = ":heavy_minus_sign:",
      label = "➖ :heavy_minus_sign:",
      insertText = "➖",
      filterText = ":heavy_minus_sign:",
    },
    {
      word = ":wrench:",
      label = "🔧 :wrench:",
      insertText = "🔧",
      filterText = ":wrench:",
    },
    {
      word = ":hammer:",
      label = "🔨 :hammer:",
      insertText = "🔨",
      filterText = ":hammer:",
    },
    {
      word = ":globe_with_meridians:",
      label = "🌐 :globe_with_meridians:",
      insertText = "🌐",
      filterText = ":globe_with_meridians:",
    },
    {
      word = ":pencil2:",
      label = "✏️ :pencil2:",
      insertText = "✏️",
      filterText = ":pencil2:",
    },
    {
      word = ":rewind:",
      label = "⏪ :rewind:",
      insertText = "⏪",
      filterText = ":rewind:",
    },
    {
      word = ":twisted_rightwards_arrows:",
      label = "🔀 :twisted_rightwards_arrows:",
      insertText = "🔀",
      filterText = ":twisted_rightwards_arrows:",
    },
    {
      word = ":package:",
      label = "📦 :package:",
      insertText = "📦",
      filterText = ":package:",
    },
    {
      word = ":alien:",
      label = "👽 :alien:",
      insertText = "👽",
      filterText = ":alien:",
    },
    {
      word = ":truck:",
      label = "🚚 :truck:",
      insertText = "🚚",
      filterText = ":truck:",
    },
    {
      word = ":page_facing_up:",
      label = "📄 :page_facing_up:",
      insertText = "📄",
      filterText = ":page_facing_up:",
    },
    {
      word = ":boom:",
      label = "💥 :boom:",
      insertText = "💥",
      filterText = ":boom:",
    },
    {
      word = ":bento:",
      label = "🍱 :bento:",
      insertText = "🍱",
      filterText = ":bento:",
    },
    {
      word = ":wheelchair:",
      label = "♿ :wheelchair:",
      insertText = "♿",
      filterText = ":wheelchair:",
    },
    {
      word = ":bulb:",
      label = "💡 :bulb:",
      insertText = "💡",
      filterText = ":bulb:",
    },
    {
      word = ":beers:",
      label = "🍻 :beers:",
      insertText = "🍻",
      filterText = ":beers:",
    },
    {
      word = ":speech_balloon:",
      label = "💬 :speech_balloon:",
      insertText = "💬",
      filterText = ":speech_balloon:",
    },
    {
      word = ":card_file_box:",
      label = "🗃️ :card_file_box:",
      insertText = "🗃️",
      filterText = ":card_file_box:",
    },
    {
      word = ":loud_sound:",
      label = "🔊 :loud_sound:",
      insertText = "🔊",
      filterText = ":loud_sound:",
    },
    {
      word = ":mute:",
      label = "🔇 :mute:",
      insertText = "🔇",
      filterText = ":mute:",
    },
    {
      word = ":busts_in_silhouette:",
      label = "👥 :busts_in_silhouette:",
      insertText = "👥",
      filterText = ":busts_in_silhouette:",
    },
    {
      word = ":children_crossing:",
      label = "🚸 :children_crossing:",
      insertText = "🚸",
      filterText = ":children_crossing:",
    },
    {
      word = ":building_construction:",
      label = "🏗️ :building_construction:",
      insertText = "🏗️",
      filterText = ":building_construction:",
    },
    {
      word = ":iphone:",
      label = "📱 :iphone:",
      insertText = "📱",
      filterText = ":iphone:",
    },
    {
      word = ":clown_face:",
      label = "🤡 :clown_face:",
      insertText = "🤡",
      filterText = ":clown_face:",
    },
    {
      word = ":egg:",
      label = "🥚 :egg:",
      insertText = "🥚",
      filterText = ":egg:",
    },
    {
      word = ":see_no_evil:",
      label = "🙈 :see_no_evil:",
      insertText = "🙈",
      filterText = ":see_no_evil:",
    },
    {
      word = ":camera_with_flash:",
      label = "📸 :camera_with_flash:",
      insertText = "📸",
      filterText = ":camera_with_flash:",
    },
    {
      word = ":alembic:",
      label = "⚗️ :alembic:",
      insertText = "⚗️",
      filterText = ":alembic:",
    },
    {
      word = ":mag:",
      label = "🔍 :mag:",
      insertText = "🔍",
      filterText = ":mag:",
    },
    {
      word = ":label:",
      label = "🏷️ :label:",
      insertText = "🏷️",
      filterText = ":label:",
    },
    {
      word = ":seedling:",
      label = "🌱 :seedling:",
      insertText = "🌱",
      filterText = ":seedling:",
    },
    {
      word = ":triangular_flag_on_post:",
      label = "🚩 :triangular_flag_on_post:",
      insertText = "🚩",
      filterText = ":triangular_flag_on_post:",
    },
    {
      word = ":goal_net:",
      label = "🥅 :goal_net:",
      insertText = "🥅",
      filterText = ":goal_net:",
    },
    {
      word = ":dizzy:",
      label = "💫 :dizzy:",
      insertText = "💫",
      filterText = ":dizzy:",
    },
    {
      word = ":wastebasket:",
      label = "🗑️ :wastebasket:",
      insertText = "🗑️",
      filterText = ":wastebasket:",
    },
    {
      word = ":passport_control:",
      label = "🛂 :passport_control:",
      insertText = "🛂",
      filterText = ":passport_control:",
    },
    {
      word = ":adhesive_bandage:",
      label = "🩹 :adhesive_bandage:",
      insertText = "🩹",
      filterText = ":adhesive_bandage:",
    },
    {
      word = ":face_with_monocle:",
      label = "🧐 :face_with_monocle:",
      insertText = "🧐",
      filterText = ":face_with_monocle:",
    },
    {
      word = ":coffin:",
      label = "⚰️ :coffin:",
      insertText = "⚰️",
      filterText = ":coffin:",
    },
    {
      word = ":test_tube:",
      label = "🧪 :test_tube:",
      insertText = "🧪",
      filterText = ":test_tube:",
    },
    {
      word = ":necktie:",
      label = "👔 :necktie:",
      insertText = "👔",
      filterText = ":necktie:",
    },
    {
      word = ":stethoscope:",
      label = "🩺 :stethoscope:",
      insertText = "🩺",
      filterText = ":stethoscope:",
    },
    {
      word = ":bricks:",
      label = "🧱 :bricks:",
      insertText = "🧱",
      filterText = ":bricks:",
    },
    {
      word = ":money_with_wings:",
      label = "💸 :money_with_wings:",
      insertText = "💸",
      filterText = ":money_with_wings:",
    },
    {
      word = ":thread:",
      label = "🧵 :thread:",
      insertText = "🧵",
      filterText = ":thread:",
    },
    {
      word = ":safety_vest:",
      label = "🦺 :safety_vest:",
      insertText = "🦺",
      filterText = ":safety_vest:",
    },
  }
end
